swagger: '2.0'
info:
  title: ArgentBank Transactions API
  version: "1.0"
  description: API pour la gestion des transactions bancaires et des informations associées sur ArgentBank

paths:
  /accounts/{accountId}/transactions:
    get:
      summary: Récupérer les transactions du mois en cours pour un compte
      description: Permet à l'utilisateur de voir toutes ses transactions pour le mois en cours.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID unique du compte bancaire de l'utilisateur
        - name: month
          in: query
          required: false
          type: string
          description: Mois pour lequel récupérer les transactions (format: YYYY-MM)
      responses:
        200:
          description: Liste des transactions pour le mois en cours
          schema:
            type: array
            items:
              $ref: '#/definitions/Transaction'
        404:
          description: Compte non trouvé
        500:
          description: Erreur serveur

  /accounts/{accountId}/transactions/{transactionId}:
    get:
      summary: Voir les détails d'une transaction
      description: Permet de voir les détails d'une transaction spécifique, y compris le type de transaction, la catégorie et les notes.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID unique du compte bancaire de l'utilisateur
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID unique de la transaction
      responses:
        200:
          description: Détails de la transaction
          schema:
            $ref: '#/definitions/TransactionDetails'
        404:
          description: Transaction non trouvée
        500:
          description: Erreur serveur

    put:
      summary: Modifier les informations supplémentaires d'une transaction
      description: Permet de modifier les informations associées à une transaction, telles que le type, la catégorie ou les notes.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID unique du compte bancaire de l'utilisateur
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID unique de la transaction
        - name: transactionData
          in: body
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
          description: Données supplémentaires à mettre à jour
      responses:
        200:
          description: Informations supplémentaires de la transaction mises à jour avec succès
          schema:
            $ref: '#/definitions/TransactionDetails'
        404:
          description: Transaction non trouvée
        400:
          description: Requête invalide
        500:
          description: Erreur serveur

    delete:
      summary: Supprimer les informations supplémentaires d'une transaction
      description: Permet de supprimer les informations supplémentaires associées à une transaction (comme la catégorie ou les notes), sans supprimer la transaction elle-même.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID unique du compte bancaire de l'utilisateur
        - name: transactionId
          in: path
          required: true
          type: string
          description: ID unique de la transaction
      responses:
        204:
          description: Informations supplémentaires supprimées avec succès
        404:
          description: Transaction non trouvée
        500:
          description: Erreur serveur

    post:
      summary: Ajouter des informations supplémentaires à une transaction
      description: Permet d'ajouter des informations supplémentaires, comme des notes ou une catégorie, à une transaction existante.
      parameters:
        - name: accountId
          in: path
          required: true
          type: string
          description: ID unique du compte bancaire de l'utilisateur
        - name: transactionData
          in: body
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
          description: Données supplémentaires à ajouter à la transaction
      responses:
        201:
          description: Informations supplémentaires ajoutées avec succès
          schema:
            $ref: '#/definitions/TransactionDetails'
        404:
          description: Transaction non trouvée
        400:
          description: Requête invalide
        500:
          description: Erreur serveur

definitions:
  Transaction:
    type: object
    properties:
      transactionId:
        type: string
        description: ID unique de la transaction
      date:
        type: string
        format: date
        description: Date de la transaction
      description:
        type: string
        description: Description de la transaction
      amount:
        type: number
        format: float
        description: Montant de la transaction
      balance:
        type: number
        format: float
        description: Solde après la transaction

  TransactionDetails:
    allOf:
      - $ref: '#/definitions/Transaction'
      - type: object
        properties:
          type:
            type: string
            description: Type de transaction (e.g., Électronique, Chèque)
          category:
            type: string
            description: Catégorie de la transaction (e.g., Alimentaire, Divertissement)
          notes:
            type: string
            description: Notes ou commentaires supplémentaires sur la transaction

  TransactionUpdate:
    type: object
    properties:
      type:
        type: string
        description: Type de transaction (e.g., Électronique, Chèque)
      category:
        type: string
        description: Catégorie de la transaction (e.g., Alimentaire, Divertissement)
      notes:
        type: string
        description: Notes ou commentaires supplémentaires sur la transaction
